export const ROLES = {
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  COMPANY_EMPLOYEE: 'COMPANY_EMPLOYEE',
  LICENSE_USER: 'LICENSE_USER',
  PRIVATE_USER: 'PRIVATE_USER',
};
